"""Planner agent."""

from typing import Any

from app.agents.base import AgentBase
from app.infra.llm.base import LLMClient
from app.schemas.plan import ResearchPlan

DEFAULT_COMPETITORS = ["Cursor", "GitHub Copilot"]
DEFAULT_DIMENSIONS = ["pricing", "features", "ecosystem"]


class Planner(AgentBase):
    """Create a research plan from the user request."""

    name = "planner"

    def __init__(self, llm: LLMClient) -> None:
        self.llm = llm

    async def run(self, state: dict[str, Any]) -> dict[str, Any]:
        """Create a validated research plan.

        Args:
            state: Workflow state containing user_query and optional requested fields.

        Returns:
            State update with plan and normalized competitors/dimensions.
        """
        query = str(state.get("user_query", ""))
        competitors = list(state.get("requested_competitors") or [])
        dimensions = list(state.get("requested_dimensions") or [])
        prompt = self._prompt(query, competitors, dimensions)
        try:
            plan = await self.llm.invoke(
                prompt=prompt,
                model_role="heavy",
                schema=ResearchPlan,
                max_tokens=1800,
                temperature=0.2,
            )
        except Exception as exc:
            plan = self._fallback_plan(query, competitors, dimensions)
            issues = [*state.get("issues", []), f"planner_fallback: {exc}"]
        else:
            issues = list(state.get("issues", []))
        return {
            "plan": plan.model_dump(),
            "competitors": [
                {"name": name, "sources": [], "evidences": []}
                for name in plan.competitors
            ],
            "current_stage": self.name,
            "issues": issues,
        }

    @staticmethod
    def _prompt(query: str, competitors: list[str], dimensions: list[str]) -> str:
        return (
            "Create a competitive research plan as JSON.\n"
            f"user_query={query}\n"
            f"requested_competitors={competitors}\n"
            f"requested_dimensions={dimensions}\n"
            "Use requested competitors and dimensions when provided."
        )

    @staticmethod
    def _fallback_plan(query: str, competitors: list[str], dimensions: list[str]) -> ResearchPlan:
        names = competitors[:6] or DEFAULT_COMPETITORS
        while len(names) < 2:
            names.append(DEFAULT_COMPETITORS[len(names)])
        dims = dimensions[:8] or DEFAULT_DIMENSIONS
        while len(dims) < 3:
            dims.append(DEFAULT_DIMENSIONS[len(dims)])
        return ResearchPlan(
            market=query or "competitive analysis",
            competitors=names,
            dimensions=dims,
            search_queries={
                name: [f"{name} {query}", f"{name} pricing features"] for name in names
            },
            required_fields={dimension: ["claim", "value", "source"] for dimension in dims},
            assumptions=["Generated by rule-based planner fallback."],
            constraints=[],
        )
